import type { NextPage } from 'next'
import Head from 'next/head'
import DatePicker from '../components/Datepicker'
import th_TH from 'antd/lib/date-picker/locale/th_TH'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h3>Thai year datepicker example</h3>
        <br />
        <br />
        
        {/* component custom datepicker */}
        <DatePicker format={'DD/MM/BBBB'} locale={th_TH} />

      </main>

    </div>
  )
}

export default Home
